### ISSUE TITLE
Slow execution in some cases

### ISSUE THREAD

**Issue by AckslD** [AckslD/nvim-revJ.lua#18]
@ram02z reported in #14 that the execution was slow. Not sure yet why this is.

**Comment by ram02z** [comment]
After some quick testing I was able to get two profile files. However, one is from a basic vimrc using vim-plug, whilst the other is my main config with about 50 plugins using packer.  Another problem with the tests is that one was performed on WSL2 and the other on my windows (vim-plug vs packer).  I disabled all plugins that had a significant execution time on my packer config and I was able to get similar performance (10% slower on packer but that could be WSL2) based on the profile data, however, I still felt the packer config had a significant delay over the basic vim-plug config. Here are the gists; [vim-plug](https://gist.github.com/ram02z/667431288452667d26f93c738db8d770#file-vim-plug) and [packer](https://gist.github.com/ram02z/667431288452667d26f93c738db8d770#file-packer).

I will come up with better tests later on the week because there were too many variables that could have affected the result and I don't think these tests are conclusive at all.

**Comment by AckslD** [comment]
Thanks @ram02z! How did you profile actually? I cannot see anything slow in the profiles, everything much below ms from what I can see, which shouldn't be noticeable. Also, there doesn't seem to be any functions from nvim-revJ in there?

**Comment by ram02z** [comment]
@AckslD Yeah that's what I am wondering too. There was no outlier in the results, perhaps it has to do with that fact that only functions tested were vim functions. I have no experience in profiling, so this was my first time but the steps I took were as follows:
- `profile start` <filename>
- `profile func *`
- Leader+j
- `exit`

**Comment by AckslD** [comment]
That's a good point about the lua hehe :) There seems to be this WIP profiler (although haven't tried it):
https://github.com/norcalli/profiler.nvim

**Comment by AckslD** [comment]
@ram02z I was experiencing some very slow performance lately as well which seems to have been caused by autocmds I have that got triggered many times when performing the formatting. This should be fixed in #21 which disables autocmds while formatting. Feel free to try it out.

**Comment by AckslD** [comment]
Hopefully closed by #21, feel free to reopen if not
